In [216]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [217]:
# Creating DataFrames using 2D arrays
studentData = [
    [100,80,10],
    [90,100,11],
    [120,70,15],
    [120,95,12],
    [80,30,15]
]
studentData = pd.DataFrame(studentData, columns=['iq','marks','package'])

In [218]:
# Creating DataFrame using Dictionary
studentData = {
                'name':['tejas','hello','world','okay','google'],
                'iq' : [100,90,120,120,80],
                'marks' : [80,100,70,95,30],
                'package' : [10,11,15,12,15]
}
studentData = pd.DataFrame(studentData)

In [219]:
# Creating DataFrames using read_csv
moviesData = pd.read_csv("/content/movies.csv") # gets imported as a DF
print(type(moviesData))
# moviesData

<class 'pandas.core.frame.DataFrame'>

In [220]:
iplData = pd.read_csv('ipl-matches.csv')
iplData

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [221]:
### Attributes and Methods of DataFrames

In [222]:
# shape
print(moviesData.shape)
print(iplData.shape)

(1629, 18)
(950, 20)

In [223]:
# dtype
print(moviesData.dtypes)

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [224]:
iplData.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [225]:
# index
print(moviesData.index)
print(iplData.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=950, step=1)

In [226]:
# columns
print(moviesData.columns)

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [227]:
print(studentData.columns)

Index(['name', 'iq', 'marks', 'package'], dtype='object')

In [228]:
# values
studentData.values

array([['tejas', 100, 80, 10],
       ['hello', 90, 100, 11],
       ['world', 120, 70, 15],
       ['okay', 120, 95, 12],
       ['google', 80, 30, 15]], dtype=object)

In [229]:
iplData.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], dtype=object)

In [230]:
moviesData.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In [231]:
 # Head and Tail

In [232]:
moviesData.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [233]:
iplData.tail()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [234]:
# Sample - randomly picks data from Df

In [235]:
moviesData.sample() # one sample data

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
92,Sonu Ke Titu Ki Sweety,tt7581902,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sonu_Ke_Titu_Ki_...,Sonu Ke Titu Ki Sweety,Sonu Ke Titu Ki Sweety,0,2018,138,Comedy|Romance,7.1,17378,"We have always been told that ""Marriage"" is a ...",Titu is going to marry a perfect woman named S...,NaN,Kartik Aaryan|Nushrat Bharucha|Sunny Singh Nij...,4 wins & 9 nominations,23 February 2018 (USA)

In [236]:
iplData.sample(5) # 5 random data

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
105,1254086,Ahmedabad,2021-05-02,2021,29,Punjab Kings,Delhi Capitals,"Narendra Modi Stadium, Ahmedabad",Delhi Capitals,field,N,Delhi Capitals,Wickets,7.0,NaN,MA Agarwal,"['P Simran Singh', 'MA Agarwal', 'CH Gayle', '...","['PP Shaw', 'S Dhawan', 'SPD Smith', 'RR Pant'...",AK Chaudhary,AY Dandekar
47,1304073,Mumbai,2022-04-16,2022,27,Royal Challengers Bangalore,Delhi Capitals,"Wankhede Stadium, Mumbai",Delhi Capitals,field,N,Royal Challengers Bangalore,Runs,16.0,NaN,KD Karthik,"['F du Plessis', 'Anuj Rawat', 'V Kohli', 'GJ ...","['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...",Chirra Ravikanthreddy,J Madanagopal
830,419109,Kolkata,2010-03-14,2009/10,4,Kolkata Knight Riders,Royal Challengers Bangalore,Eden Gardens,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,7.0,NaN,MK Tiwary,"['BJ Hodge', 'MK Tiwary', 'SC Ganguly', 'CA Pu...","['JH Kallis', 'SP Goswami', 'MK Pandey', 'V Ko...",HDPK Dharmasena,AM Saheba
476,829735,Ahmedabad,2015-04-19,2015,15,Rajasthan Royals,Chennai Super Kings,"Sardar Patel Stadium, Motera",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,8.0,NaN,AM Rahane,"['AM Rahane', 'SR Watson', 'SPD Smith', 'KK Na...","['DR Smith', 'BB McCullum', 'SK Raina', 'F du ...",AK Chaudhary,M Erasmus
702,501271,Chennai,2011-05-28,2011,Final,Chennai Super Kings,Royal Challengers Bangalore,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,58.0,NaN,M Vijay,"['MEK Hussey', 'M Vijay', 'MS Dhoni', 'SK Rain...","['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...",Asad Rauf,SJA Taufel

In [237]:
# info

In [238]:
moviesData.info() # info of columns, non null data type, dtype: object means string, int64, etc, dtypes, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [239]:
iplData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [240]:
# Describe - provides mathematical summary

In [241]:
moviesData.describe() # 4 numberical columns, operations performed : count, mean, std, min, max etc

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [242]:
iplData.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [243]:
# isnull - does my DF have missing values

In [244]:
moviesData.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [245]:
moviesData.isnull().sum() # provides sum of each columns where values are true
# eg: in title_x, wiki_link columns - no null values
# poster_path has 103 null values

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [246]:
# duplicated - does my DF have duplicate values

In [247]:
moviesData.duplicated()
# False means - that particular row in the DF is not repeated

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [248]:
print(moviesData.duplicated().sum()) # provides total number of duplicated rows

0

In [249]:
studentData = [
    [100,80,10],
    [80,30,15],
    [90,100,11],
    [120,95,12],
    [80,30,15]
]
studentData = pd.DataFrame(studentData, columns=['iq','marks','package'])

In [250]:
studentData.duplicated()
# prints the item which is dulplicated

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [251]:
studentData.duplicated().sum()

np.int64(1)

In [252]:
studentData = [
    [80,30,15],
    [80,30,15],
    [90,100,11],
    [120,95,12],
    [80,30,15],
    [90,100,11]
]
studentData = pd.DataFrame(studentData, columns=['iq','marks','package'])

In [253]:
studentData.duplicated()

0    False
1     True
2    False
3    False
4     True
5     True
dtype: bool

In [254]:
studentData.duplicated().sum() # there are 3 duplicated row

np.int64(3)

In [255]:
## Rename Function - renames the column name

In [256]:
studentData

    iq  marks  package
0   80     30       15
1   80     30       15
2   90    100       11
3  120     95       12
4   80     30       15
5   90    100       11

In [257]:
studentData.rename(columns = {'marks':'percent', 'package':'ctc'}) # doesnot change permanently

    iq  percent  ctc
0   80       30   15
1   80       30   15
2   90      100   11
3  120       95   12
4   80       30   15
5   90      100   11

In [258]:
studentData

    iq  marks  package
0   80     30       15
1   80     30       15
2   90    100       11
3  120     95       12
4   80     30       15
5   90    100       11

In [259]:
studentData.rename(columns = {'marks':'percent', 'package':'ctc'}, inplace=True) # changes the name permanently

In [260]:
studentData

    iq  percent  ctc
0   80       30   15
1   80       30   15
2   90      100   11
3  120       95   12
4   80       30   15
5   90      100   11

In [261]:
### MAthematical Function

In [262]:
# Sum
moviesData

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [263]:
moviesData.sum(numeric_only= True) # adds only those column which are Numeric

is_adult                 0.0
year_of_release    3274720.0
imdb_rating           9053.1
imdb_votes         8770965.0
dtype: float64

In [264]:
studentData

    iq  percent  ctc
0   80       30   15
1   80       30   15
2   90      100   11
3  120       95   12
4   80       30   15
5   90      100   11

In [265]:
studentData.sum() # since all columns are numeric, performs sum on all columns

iq         540
percent    385
ctc         79
dtype: int64

In [266]:
studentData.sum(axis = 1) # performs sum on row data

0    125
1    125
2    201
3    227
4    125
5    201
dtype: int64

In [267]:
# Axis = 1 : Row
# Axis = 0 : column

In [268]:
# mean
studentData.mean(axis = 0)

iq         90.000000
percent    64.166667
ctc        13.166667
dtype: float64

In [269]:
studentData.mean(axis = 1)

0    41.666667
1    41.666667
2    67.000000
3    75.666667
4    41.666667
5    67.000000
dtype: float64

In [270]:
moviesData.mean(numeric_only=True)

is_adult              0.000000
year_of_release    2010.263966
imdb_rating           5.557459
imdb_votes         5384.263352
dtype: float64

In [271]:
iplData.mean(numeric_only=True)

ID        830485.247368
Margin        17.056867
dtype: float64

In [272]:
studentData.min()

iq         80
percent    30
ctc        11
dtype: int64

In [273]:
studentData.max(axis=0)

iq         120
percent    100
ctc         15
dtype: int64

In [274]:
studentData.std(axis=1)

0    34.034296
1    34.034296
2    48.754487
3    56.536124
4    34.034296
5    48.754487
dtype: float64

In [275]:
studentData.var()

iq          240.000000
percent    1404.166667
ctc           4.166667
dtype: float64

In [276]:
studentData.mode(axis=0)

   iq  percent  ctc
0  80       30   15

In [277]:
studentData.median(axis = 1)

0    30.0
1    30.0
2    90.0
3    95.0
4    30.0
5    90.0
dtype: float64

In [278]:
### Fetching Data
iplData.columns = [name.lower() for name in iplData.columns] # converts all names of the column to Lower Case
moviesData.columns = [name.lower() for name in moviesData.columns] # converts all names of the column to Lower Case

In [279]:
# fetching Movie Name

In [280]:
print(moviesData['title_x'].head())
print(type(moviesData['title_x'])) # Series Data type - fetching only one column is Series

0                Uri: The Surgical Strike
1                           Battalion 609
2    The Accidental Prime Minister (film)
3                         Why Cheat India
4                         Evening Shadows
Name: title_x, dtype: object
<class 'pandas.core.series.Series'>

In [281]:
iplData['venue'].head(5)

0    Narendra Modi Stadium, Ahmedabad
1    Narendra Modi Stadium, Ahmedabad
2               Eden Gardens, Kolkata
3               Eden Gardens, Kolkata
4            Wankhede Stadium, Mumbai
Name: venue, dtype: object

In [282]:
# Fetching multiple columns
moviesData[['actors','year_of_release','title_x']].head() # this is a dataframe (And not series)

,actors,year_of_release,title_x
0,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,2019,Uri: The Surgical Strike
1,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,2019,Battalion 609
2,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,2019,The Accidental Prime Minister (film)
3,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,2019,Why Cheat India
4,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,2018,Evening Shadows

In [283]:
iplData[['team1','team2','tosswinner','winningteam']]

,team1,team2,tosswinner,winningteam
0,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings
...,...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders

In [284]:
studentData = {
                'name':['tejas','hello','world','okay','google'],
                'iq' : [100,90,120,120,80],
                'marks' : [80,100,70,95,30],
                'package' : [10,11,15,12,15]
}
studentData = pd.DataFrame(studentData)
studentData

     name   iq  marks  package
0   tejas  100     80       10
1   hello   90    100       11
2   world  120     70       15
3    okay  120     95       12
4  google   80     30       15

In [285]:
studentData.set_index('name', inplace=True) # making the name as index

In [286]:
# Fetching The Row

# iloc - searches using index position
# loc - searches using index labels

In [287]:
print(moviesData.iloc[0]) # gives the first row
print(type(moviesData.iloc[0]))  # is a series

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

In [288]:
moviesData.iloc[:5] # multiple rows - from 0 to 4

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [289]:
moviesData.iloc[:20:2] # step count = 2

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
12,Hum Chaar,tt9319812,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hum_Chaar,Hum chaar,Hum chaar,0,2019,143,Drama,5.6,183,The story of the film revolves around four col...,The story of the film revolves around four col...,NaN,Prit Kamani|Simran Sharma|Anshuman Malhotra|Tu...,NaN,15 February 2019 (India)
14,Sonchiriya,tt8108200,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sonchiriya,Sonchiriya,Sonchiriya,0,2019,143,Action|Crime|Drama,7.5,2322,This is the story of a group of rebels in Cham...,Set in the Chambal valley the film follows th...,NaN,Sushant Singh Rajput|Bhumi Pednekar|Manoj Bajp...,NaN,1 March 2019 (India)
16,Mard Ko Dard Nahi Hota,tt8055888,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mard_Ko_Dard_Nah...,Mard Ko Dard Nahin Hota,Mard Ko Dard Nahin Hota,0,2018,134,Action|Comedy,7.4,3969,It is a story of a young boy Surya who has a r...,It is a story of a young boy Surya who has a r...,NaN,Abhimanyu Dasani|Radhika Madan|Prateek Parmar|...,2 wins & 2 nominations,22 March 2019 (USA)
18,Photograph (film),tt7778680,https://upload.wikimedia.org/wikipedia/en/7/71...,https://en.wikipedia.org/wiki/Photograph_(film),Photograph,Photograph,0,2019,110,Drama|Romance,6.9,2391,Two lives intersect in Mumbai and go along tog...,A struggling street photographer in Mumbai pr...,NaN,Nawazuddin Siddiqui|Sanya Malhotra|Sachin Khed...,NaN,17 May 2019 (USA)

In [290]:
moviesData.iloc[[0,4,5]] # gives row 0, 4, and 5

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [291]:
# loc

In [292]:
studentData.loc['tejas'] # gives row with name 'tejas'

iq         100
marks       80
package     10
Name: tejas, dtype: int64

In [293]:
studentData.loc['tejas':'okay'] # from tejas to okay (both included)

        iq  marks  package
name
tejas  100     80       10
hello   90    100       11
world  120     70       15
okay   120     95       12

In [294]:
studentData.loc['tejas':'okay':2]  # step count = 2

        iq  marks  package
name
tejas  100     80       10
world  120     70       15

In [295]:
studentData.loc[['tejas','okay','hello']]

        iq  marks  package
name
tejas  100     80       10
okay   120     95       12
hello   90    100       11

In [296]:
studentData.iloc[0] # data at 0th index

iq         100
marks       80
package     10
Name: tejas, dtype: int64

In [297]:
### Selecting Both Rows and Columns together
moviesData.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [298]:
moviesData.iloc[:3][['title_x','imdb_id','poster_path']] # fetches first 3 row and first 3 column

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [299]:
moviesData.iloc[0:3, 0:3] # fetches first 3 row and first 3 column

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [300]:
moviesData.loc[0:3, 'title_x':'poster_path'] # fetches first 3 row and first 3 column

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...

In [301]:
moviesData.loc[0:3, 'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...

In [302]:
studentData

         iq  marks  package
name
tejas   100     80       10
hello    90    100       11
world   120     70       15
okay    120     95       12
google   80     30       15

In [303]:
###### Filtering the data

In [304]:
iplData.head(3)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,player_of_match,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [305]:
# find all the final winners
iplData[iplData['matchnumber'] == 'Final'][['winningteam','season']]

               winningteam   season
0           Gujarat Titans     2022
74     Chennai Super Kings     2021
134         Mumbai Indians  2020/21
194         Mumbai Indians     2019
254    Chennai Super Kings     2018
314         Mumbai Indians     2017
373    Sunrisers Hyderabad     2016
433         Mumbai Indians     2015
492  Kolkata Knight Riders     2014
552         Mumbai Indians     2013
628  Kolkata Knight Riders     2012
702    Chennai Super Kings     2011
775    Chennai Super Kings  2009/10
835        Deccan Chargers     2009
892       Rajasthan Royals  2007/08

In [306]:
# how many super overs finshes have occured
iplData[iplData['superover'] == 'Y'].shape[0]

14

In [307]:
# how many matches has csk won in kolkata
iplData[iplData['city'] == 'Kolkata'] # matches in kolkata
iplData[(iplData['city'] == 'Kolkata') & (iplData['winningteam'] == 'Chennai Super Kings')][['city','winningteam']].shape[0]

5

In [308]:
# toss winner is the match winner in percentage
(iplData[iplData['tosswinner'] == iplData['winningteam']].shape[0])/iplData.shape[0]*100

51.473684210526315

In [309]:
moviesData.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [310]:
# movies with ratings higher than 8 and votes>10000
movieNames = moviesData[(moviesData['imdb_rating']>8) & (moviesData['imdb_votes']>10000)]['title_x']
movieCount = movieNames.shape[0]

print(movieNames)
print(movieCount)

0          Uri: The Surgical Strike
11                        Gully Boy
37                Article 15 (film)
40                  Super 30 (film)
143                         Tumbbad
146                       Andhadhun
325                Pink (2016 film)
354                   Dangal (film)
418                          Masaan
426            Drishyam (2015 film)
436                   Talvar (film)
469               Queen (2014 film)
536                   Haider (film)
566                     Ugly (film)
567                       PK (film)
589                    Vishwaroopam
612              Bhaag Milkha Bhaag
638                   Shahid (film)
668         Paan Singh Tomar (film)
669                         Kahaani
693              Gangs of Wasseypur
694     Gangs of Wasseypur – Part 2
709                          Barfi!
714                OMG – Oh My God!
778        Zindagi Na Milegi Dobara
869               Udaan (2010 film)
912                        3 Idiots
930                   Gulaal (film)
1058       Black Friday (2007 film)
1066                 Chak De! India
1127               Taare Zameen Par
1180               Khosla Ka Ghosla
1183           Lage Raho Munna Bhai
1188             Omkara (2006 film)
1195                Rang De Basanti
1223              Black (2005 film)
1252                   Iqbal (film)
1384                         Swades
1403            Munna Bhai M.B.B.S.
1554     The Legend of Bhagat Singh
1567                         Lagaan
1568                         Lagaan
1571                 Dil Chahta Hai
Name: title_x, dtype: object
43

In [311]:
# Action movies with rating higher than 7.5
moviesData['genres']

0       Action|Drama|War
1                    War
2        Biography|Drama
3            Crime|Drama
4                  Drama
              ...
1624               Drama
1625               Drama
1626        Comedy|Drama
1627              Action
1628       Drama|Romance
Name: genres, Length: 1629, dtype: object

In [312]:
toStr = moviesData['genres'].str # converting genres into str
mid = toStr.split('|') # spliting on '|'

In [313]:
mask1 = mid.apply(lambda x : 'Action' in x)
mask2 = moviesData['imdb_rating'] > 7.5
mask3 = moviesData['imdb_votes'] > 10000

In [314]:
moviesData[mask1 & mask2 & mask3].shape[0]

25

In [315]:
mask1 = moviesData['genres'].str.split('|').apply(lambda x : 'Action' in x)
mask2 = moviesData['imdb_rating'] > 7.5
mask3 = moviesData['imdb_votes'] > 10000

In [316]:
moviesData[mask1 & mask2 & mask3].shape[0]

25

In [317]:
mask1 = moviesData['genres'].str.contains('Action')
mask2 = moviesData['imdb_rating'] > 7.5
mask3 = moviesData['imdb_votes'] > 10000
moviesData[mask1 & mask2 & mask3].shape[0]

25

In [318]:
# Write a function that can return the track record of 2 teams against each other

In [319]:
### Adding new columns

# adding new column Country to the moviesData DF - newOne
moviesData['country'] = "India"

In [320]:
moviesData.head(5)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

In [321]:
# adding new columns from the existing rows
# actors column has null values also. Therefore we have to drop them dropna
newMoviesData = moviesData.dropna().copy() # creates a brand new copy instead of a view
lead = newMoviesData['actors'].str.split('|').apply(lambda x:x[0])
newMoviesData['leadactors'] = lead

In [322]:
newMoviesData.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country,leadactors
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal

In [323]:
### astype - changes the datatype of a given column
iplData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               950 non-null    int64
 1   city             899 non-null    object
 2   date             950 non-null    object
 3   season           950 non-null    object
 4   matchnumber      950 non-null    object
 5   team1            950 non-null    object
 6   team2            950 non-null    object
 7   venue            950 non-null    object
 8   tosswinner       950 non-null    object
 9   tossdecision     950 non-null    object
 10  superover        946 non-null    object
 11  winningteam      946 non-null    object
 12  wonby            950 non-null    object
 13  margin           932 non-null    float64
 14  method           19 non-null     object
 15  player_of_match  946 non-null    object
 16  team1players     950 non-null    object
 17  team2players     950 non-null    object
 18  umpire1          950 non-null    object
 19  umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [324]:
# change the dtype of id to into int32
iplData['id'] = iplData['id'].astype('int32')

In [325]:
iplData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               950 non-null    int32
 1   city             899 non-null    object
 2   date             950 non-null    object
 3   season           950 non-null    object
 4   matchnumber      950 non-null    object
 5   team1            950 non-null    object
 6   team2            950 non-null    object
 7   venue            950 non-null    object
 8   tosswinner       950 non-null    object
 9   tossdecision     950 non-null    object
 10  superover        946 non-null    object
 11  winningteam      946 non-null    object
 12  wonby            950 non-null    object
 13  margin           932 non-null    float64
 14  method           19 non-null     object
 15  player_of_match  946 non-null    object
 16  team1players     950 non-null    object
 17  team2players     950 non-null    object
 18  umpire1          950 non-null    object
 19  umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB

In [326]:
# change the datatype of season to category
iplData['season'] = iplData['season'].astype('category')
iplData['team1'] = iplData['team1'].astype('category')
iplData['team2'] = iplData['team2'].astype('category')

In [329]:
iplData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               950 non-null    int32
 1   city             899 non-null    object
 2   date             950 non-null    object
 3   season           950 non-null    category
 4   matchnumber      950 non-null    object
 5   team1            950 non-null    category
 6   team2            950 non-null    category
 7   venue            950 non-null    object
 8   tosswinner       950 non-null    object
 9   tossdecision     950 non-null    object
 10  superover        946 non-null    object
 11  winningteam      946 non-null    object
 12  wonby            950 non-null    object
 13  margin           932 non-null    float64
 14  method           19 non-null     object
 15  player_of_match  946 non-null    object
 16  team1players     950 non-null    object
 17  team2players     950 non-null    object
 18  umpire1          950 non-null    object
 19  umpire2          950 non-null    object
dtypes: category(3), float64(1), int32(1), object(15)
memory usage: 127.4+ KB